portal/urls.py
from django.urls import path
from .views import *

app_name = 'portal'
urlpatterns = [
    path('', index_view, name='index'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_form, name='login'),
    path('contactus/', contact_us_form, name='contactus'),
    path('profile/', profile_view, name='profile'),
    path('settings/', Settings.as_view(), name='settings'),
    path('panel/', userpanel_view, name='panel'),
    path('create_course/',CreateCourse.as_view(),name='create_course'),
    path('delete/',delete_account_view,name='delete_account')
]

webdjango_project/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portal/', include('portal.urls'))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/models.py
import django.contrib.auth.models
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import AbstractUser


class UserProfile(AbstractUser):
    bio = models.CharField(max_length=150, blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/', default='static/portal/default_avatar.jpg')
    POSSIBLE_GENDER = (
        (None, 'Would rather not specify'),
        (1, 'Male'),
        (2, 'Female')
    )
    gender = models.IntegerField(choices=POSSIBLE_GENDER, null=True, blank=True)


# Create your models here.
class Course(models.Model):
    department = models.CharField(max_length=150)
    name = models.CharField(max_length=150)
    course_number = models.IntegerField()
    group = models.IntegerField()
    professor_name = models.CharField(max_length=150)
    start_time = models.TimeField()
    end_time = models.TimeField()

    DAYS_OF_WEEK = (
        (0, 'Saturday'),
        (1, 'Sunday'),
        (2, 'Monday'),
        (3, 'Tuesday'),
        (4, 'Wednesday'),
    )
    day_1 = models.IntegerField(choices=DAYS_OF_WEEK, null=False, )
    # validators=MinValueValidator(0, message="The first day cannot be empty!"))
    day_2 = models.IntegerField(choices=DAYS_OF_WEEK, null=True, blank=True)
    users = models.ManyToManyField(UserProfile)

portal/forms.py
from django import forms
# from django.contrib.auth.models import User

from .models import Course, UserProfile
from django.contrib.auth import authenticate
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.contrib.auth.models import Group

prof_group, created = Group.objects.get_or_create(name='Professor')
std_group, created = Group.objects.get_or_create(name='Student')


class SettingsForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar', 'first_name', 'last_name', 'gender', 'bio')

    def clean(self):
        super(SettingsForm, self).clean()
        if self.cleaned_data.get('last_name') == '':
            self.cleaned_data.pop('last_name')
        if self.cleaned_data.get('first_name') == '':
            self.cleaned_data.pop('first_name')
        return self.cleaned_data


class CourseCreateForm(forms.ModelForm):
    # day_1 = forms.IntegerField(choices=Course.DAYS_OF_WEEK, required=True)
    # day_2 = forms.IntegerField(required=False, choices=Course.DAYS_OF_WEEK)

    class Meta:
        model = Course
        fields = '__all__'


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    account_type = forms.ChoiceField(choices=((prof_group.id, 'Professor'), (std_group.id, 'Student')))

    class Meta:
        model = UserProfile
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

        error_messages = {
            'username': {
                "unique": "A user with that username already exists. CUSTOM!",

            }
        }

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            self.add_error('confirm_password', "Password and Password Repeat do not match! CUSTOM")
        return cleaned_data

    def save(self, commit=True):
        super(RegisterForm, self).save(commit)
        u = UserProfile.objects.get(username=self.cleaned_data.get('username'))
        u.set_password(self.cleaned_data.get('password'))
        u.save()
        u.groups.add(self.cleaned_data.get('account_type'))
        print(u.groups.get())
        return u


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput())


class ContactForm(forms.Form):
    form_title = forms.CharField(max_length=150, label="Title")
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea, validators=[MinLengthValidator(10, 'Message Too Short!'),
                                                              MaxLengthValidator(250, "Message Too Long!")])

portal/views.py
import django.contrib.auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render,redirect
from django.views import generic
from django.contrib.auth.models import User
from .forms import LoginForm, ContactForm, RegisterForm, SettingsForm, CourseCreateForm
from .models import Course, UserProfile
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from django.conf import settings


# Create your views here.

def index_view(request):
    return render(request, 'portal/index.html')


@login_required
def logout_view(request):
    logout(request)
    return render(request, 'portal/logout.html')


@require_http_methods(['POST', 'GET'])
def login_form(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data.get('username'),
                                password=form.cleaned_data.get('password'))
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(redirect_to=reverse_lazy('portal:index'))
            else:
                return render(request, 'portal/login.html',
                              {'form': form, 'invalid_prev_login': True})
    else:
        form = LoginForm()
    return render(request, 'portal/login.html', {'form': form})


@login_required
def profile_view(request):
    return render(request, "portal/profile.html")


@require_http_methods(['POST', 'GET'])
def contact_us_form(request):
    if request.method == "POST":
        form = ContactForm(data=request.POST)
        if form.is_valid():
            message = f"SENDER EMAIL:{form.cleaned_data.get('email')}\nSENDER TEXT:\n" \
                      f"{form.cleaned_data.get('text')}"
            subject = form.cleaned_data.get('form_title')
            email_from = settings.EMAIL_HOST_USER

            send_mail(subject, message, email_from, settings.EMAIL_RECIPIENT)
            return render(request, 'portal/contact_success.html')
        else:
            return render(request, 'portal/contact_us.html',
                          {'form': form, 'invalid_prev_fill': True})
    else:
        form = ContactForm()
    return render(request, 'portal/contact_us.html', {'form': form})


class Settings(LoginRequiredMixin, generic.edit.UpdateView):
    template_name = 'portal/show_form.html'
    model = UserProfile
    form_class = SettingsForm

    success_url = reverse_lazy('portal:profile')

    def get_object(self, queryset=None):
        return self.request.user


class Register(generic.CreateView):
    template_name = 'portal/show_form.html'
    model = UserProfile
    form_class = RegisterForm
    success_url = reverse_lazy('portal:index')


from .mixins import SuperUserRequiredMixin


class CreateCourse(SuperUserRequiredMixin, generic.CreateView):
    template_name = 'portal/show_form.html'
    model = Course
    form_class = CourseCreateForm
    success_url = reverse_lazy('portal:panel')


# def user_panel(request):
#     return render(request, 'portal/panel.html')
#
#
# class UserPanelView(LoginRequiredMixin,generic.ListView):
#     model = Course
#     template_name = 'portal/panel.html'
#     context_object_name = 'courses'
#

register_active = False


@login_required
@require_http_methods(['GET', 'POST'])
def delete_account_view(request):
    if request.method == 'POST':
        current_user = request.user
        logout(request)
        current_user.delete()
        return redirect('portal:index')
    else:
        return render(request,'portal/delete_confirm.html')



@require_http_methods(['GET', 'POST'])
@login_required
def userpanel_view(request):
    global register_active
    if request.method == "POST":
        if request.POST.get('registeration', '') == '1':
            register_active = True
        elif request.POST.get('registeration', '') == '0':
            register_active = False
        course_id = request.POST.get('c_id', '')
        course_group = request.POST.get('c_group', '')
        if course_id != '' and course_group != '':
            course = Course.objects.filter(course_number=course_id, group=course_group).first()
            if course is not None:
                course.users.add(request.user)
                course.save()
        course_id = request.POST.get('c_id_drop', '')
        course_group = request.POST.get('c_group_drop', '')
        if course_id != '' and course_group != '':
            course = Course.objects.filter(course_number=course_id, group=course_group).first()
            if course is not None:
                course.users.remove(request.user)
                course.save()
    my_course = Course.objects.filter(users__username=request.user.get_username())
    courses = Course.objects.exclude(course_number__in=my_course.values_list('course_number', flat=True))

    return render(request, 'portal/panel.html', {'courses': courses, 'selection_active': register_active,
                                                 'my_courses': my_course})

portal/templates/portal/base.html
{% load static %}
<link href="{% static "portal/style.css" %}" rel="stylesheet"/>
<ul id="navbar" class="horizontal">
    {% if request.user.is_authenticated %}
        <li><a id="profile" href="{% url 'portal:profile' %}">Profile</a></li>
        <li><a id="panel" href="{% url 'portal:panel' %}">Panel</a></li>
        <li><a id="del" href="{% url 'portal:delete_account' %}">Delete Account</a></li>
        {% if request.user.is_superuser %}
            <li><a id="make_new_course" href="{% url 'portal:create_course' %}">Create Course</a></li>
        {% endif %}
        <li><a id="logout" href="{% url 'portal:logout' %}">Logout</a></li>
    {% else %}
        <li><a id="login" href="{% url 'portal:login' %}">Login</a></li>
        <li><a id="register" href="{% url 'portal:register' %}">Register</a></li>

    {% endif %}
    <li><a id="contactus" href="{% url 'portal:contactus' %}">Contact Us</a></li>
    <li style="float:right"><a id="homepage" href="{% url 'portal:index' %}">Homepage</a></li>
</ul>
<div id="content">
    {% block content %}{% endblock %}
</div>

portal/templates/portal/contact_success.html
{% extends "portal/base.html" %}
{% block content %}
    <ul class="vertical">
        <li>Contact us form filled successfully</li>
    </ul>
{% endblock %}

portal/templates/portal/contact_us.html
{% extends "portal/base.html" %}
{% block content %}
    <ul class="vertical" style="width: auto">
        {% if invalid_prev_fill %}
            <p>Error in filled data!</p><br/><br/>
        {% endif %}
        <form action="{% url 'portal:contactus' %}" method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <input type="submit" value="Submit">

        </form>
    </ul>
{% endblock %}

portal/templates/portal/course_picker.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

portal/templates/portal/delete_confirm.html
{% extends "portal/base.html" %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <ul class="vertical">
            <li>Are you sure you want to delete your account? This action is non reversible</li>
            <input type="submit" value="Confirm">
        </ul>
    </form>
{% endblock %}

portal/templates/portal/index.html
{% extends "portal/base.html" %}
{% block content %}
<ul class="vertical"> Welcome to the ERegistrar.</ul>
{% endblock %}

portal/templates/portal/login.html
{% extends "portal/base.html" %}
{% block content %}
    <ul class="vertical">
        {% if invalid_prev_login %}
            <p>Invalid username/password combination!</p><br/>
        {% endif %}
        <form action="{% url 'portal:login' %}" method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <input type="submit" value="Submit">

        </form>
    </ul>
{% endblock %}

portal/templates/portal/logout.html
{% extends "portal/base.html" %}
{% block content %}
<ul class="vertical">Logout successful!</ul>
{% endblock %}

portal/templates/portal/panel.html
{% extends "portal/base.html" %}
{% block content %}
    <ul class="vertical" style="width: auto">
        {% for course in courses %}
            <ul id='course_{{ course.course_number }}_{{ course.group }}' class="horizontal2 gray">
                <li><a>Department: {{ course.department }}</a></li>
                <li><a>Course Name: {{ course.name }}</a></li>
                <li><a>Course Number: {{ course.course_number }}</a></li>
                <li><a>Group: {{ course.group }}</a></li>
                <li><a>Professor: {{ course.professor_name }}</a></li>
                <li><a>Start Time: {{ course.start_time }}</a></li>
                <li><a>End Time: {{ course.end_time }}</a></li>
                <li><a>Day 1: {{ course.get_day_1_display }}</a></li>
                {% if course.day_2 %}
                    <li><a>Day 2: {{ course.get_day_2_display }}</a></li>
                {% endif %}
                {% if selection_active %}
                    <li>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="c_id" value="{{ course.course_number }}"/>
                            <input type="hidden" name="c_group" value="{{ course.group }}"/>
                            <a href="#" onclick="event.preventDefault(); this.parentNode.submit()" class="active">Register</a>

                        </form>

                    </li>
                {% endif %}
            </ul>
        {% endfor %}
        <li>My Courses</li>
        <ul class="vertical2">
            {% for course in my_courses %}
                <ul id='course_{{ course.course_number }}_{{ course.group }}' class="horizontal2 gray">
                    <li><a>Department: {{ course.department }}</a></li>
                    <li><a>Course Name: {{ course.name }}</a></li>
                    <li><a>Course Number: {{ course.course_number }}</a></li>
                    <li><a>Group: {{ course.group }}</a></li>
                    <li><a>Professor: {{ course.professor_name }}</a></li>
                    <li><a>Start Time: {{ course.start_time }}</a></li>
                    <li><a>End Time: {{ course.end_time }}</a></li>
                    <li><a>Day 1: {{ course.get_day_1_display }}</a></li>
                    {% if course.day_2 %}
                        <li><a>Day 2: {{ course.get_day_2_display }}</a></li>
                    {% endif %}
                    {% if selection_active %}
                        <li>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="c_id_drop" value="{{ course.course_number }}"/>
                                <input type="hidden" name="c_group_drop" value="{{ course.group }}"/>
                                <a href="#" onclick="event.preventDefault(); this.parentNode.submit()" class="active">Drop</a>

                            </form>

                        </li>
                    {% endif %}
                </ul>
            {% endfor %}
        </ul>
        {% if request.user.is_superuser %}
            <li><a id="make_new_course_link" href="{% url 'portal:create_course' %}">Create Course</a></li>
            {% if selection_active %}
                <li>
                    <form action="{% url 'portal:panel' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="registeration" value="0"/>
                        <a id="stop_course_select" href="#" onclick="event.preventDefault(); this.parentNode.submit()">End
                            Registeration</a>
                    </form>
                </li>
            {% else %}
                <li>
                    <form action="{% url 'portal:panel' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="registeration" value="1"/>
                        <a id="start_course_select" href="#" onclick="event.preventDefault(); this.parentNode.submit()">Start
                            Registeration</a>
                    </form>
                </li>
            {% endif %}


        {% endif %}
    </ul>
{% endblock %}

portal/templates/portal/profile.html
{% extends "portal/base.html" %}
{% block content %}
    <ul class="vertical" style="width: auto">
        <li><img src="{{ request.user.avatar.url }}" style="height: 300px" /></li>
        <li> Username: {{ request.user.username }}</li>
        <li> First Name: {{ request.user.first_name }}</li>
        <li> Last Name: {{ request.user.last_name }}</li>
        <li> Gender: {{ request.user.get_gender_display }}</li>
        <li>Roles:</li>
            {% for g in request.user.groups.all %}
                <li>&emsp;{{ g.name }}</li>
            {% endfor %}

        <li>Biography: <br/>&emsp;&emsp;{{ request.user.bio | safe }}</li>
        <li><a href="{% url 'portal:settings' %}">>Incorrect data? Edit here.</a></li>


    </ul>
{% endblock %}

portal/templates/portal/register.html
{% extends "portal/base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    <ul class="vertical">
    {{ form.as_p }}
    <input type="submit" value="Save">
    </ul>
</form>
{% endblock %}

portal/templates/portal/show_form.html
{% extends "portal/base.html" %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <ul class="vertical">
            {{ form.as_p }}
            <input type="submit" value="Save">
        </ul>
    </form>
{% endblock %}